#!/bin/sh
#
# SPDX-License-Identifier: GPL-2.0-only

chars='
0
1
2
3
4
5
6
7
8
9

A
B
C
D
E
F
G
H
I
J
K
L
M
N
O
P
Q
R
S
T
U
V
W
X
Y
Z
'

exit_status=0

dir_name=sounds
if ! mkdir -p "$dir_name"; then
    echo 1>&2 "[ERR] Failed to sounds '$dir_name'"
    exit 2
fi

for text in $chars richtig nochmal; do
    if ! gtts-cli --lang de --output "$dir_name/$text.mp3" "$text"; then
        echo 1>&2 "[WARN] Failed to create audio for '$text'"
	exit_status=3
    fi
done

exit "$exit_status"
